### ISSUE TITLE
UICollectionViewFlowLayout

### ISSUE THREAD

**Issue by Bellaposa** [maxoly/PulsarKit#3]
Hello! This isn't an issue but a "help wanted". 

I need to replicate this custom `UICollectionViewFlowLayout` layout (image). 
Using: 
- `collectionView(_:layout:insetForSectionAt:)` 

- `collectionView(_:layout:sizeForItemAt:)`
 I'm able to replicate the layout.

I'm not able to replicate the layout using PulsarKit and in particular I tried all the suggested layouts.
The elements are not on the same row even if I set a little width size.

Do you have any suggestions?

Thanks 

<img width="281" alt="Screenshot 2020-07-17 at 22 20 53" src="https://user-images.githubusercontent.com/16580320/87827774-d5b28300-c87b-11ea-96e0-5e5d2fd5d73f.png">

**Comment by maxoly** [comment]
Hi @Bellaposa, apologies for the delayed response. 

With PulsarKit 1.4.0 you can use the new `SplittedSize`.

**If you want a fixed number of blocks in width and height**
`SplittedSize(numOfElementsInWidth: 2, numOfElementsInHeight:  4)`

**If you want a fixed number of blocks in width and dynamic height (autolayout)** 
`SplittedSize(numOfElementsInWidth: 2)`

**If you want a fixed number of blocks in width and your specific sizable for height** 
`SplittedSize(numOfElementsInWidth: 2, heightSize: FixedSize(height: 100))`
